export const SENDING_MESSAGE = "SENDING_MESSAGE";
export const SEND_MESSAGE_COMPLETE = "SEND_MESSAGE_COMPLETE";
export const RECEIVE_MESSAGE = "RECEIVE_MESSAGE";

export const WRITING_MESSAGE = "WRITING_MESSAGE";
